import { Box, Typography } from "@mui/material";

import AppContainer from "../../CommonComponents/AppContainer";
import banner from "./pexels-markus-spiske-114296.jpg";
import layer from "../../assets/Rectangle 669.png";
import styled from "styled-components";

const Container = styled(Box)`
  display: flex;
  flex-direction: column;
`;

const BannerImage = styled.img`
  width: 100%;
  max-height: 200px;
  object-fit: cover;
`;

const StyledImage5 = styled.img`
  width: 100%;
  max-height: 200px;
  object-fit: cover;
  position: absolute;
`;

export default function TermsandConditions() {
  return (
    <Box mb={"90px"}>
      <Container>
        <BannerImage src={banner} alt="banner" />
        <StyledImage5 src={layer} alt="background" />
      </Container>
      <Box pt={"30px"}>
        <Typography
          fontWeight={"bold"}
          position={"absolute"}
          top={{ xs: "28%", sm: "25%", md: "28%", lg: "28%" }}
          left={"11%"}
          color={"white"}
          fontSize={{ xs: "20px", sm: "20px", md: "42px", lg: "42px" }}
        >
          Terms of Services
        </Typography>
      </Box>

      <AppContainer maxWidth={1180}>
        <Box>
          <Typography>
            By using or visiting website, mobile applications, software, data
            feeds, and services provided to you (collectively the "Service") you
            signify your agreement to these terms and conditions (the "Terms of
            Service") and privacy policy (the “Privacy Policy”) of the Company.
            If you do not agree to any of these terms, please do not use the
            Service.
            <br />
            <br />
            Welcome to FABOProperties.com
            <br />
            <br />
            We are a digital real estate advertising / marketing and seller
            platform connecting people with the real estate market.
            FABOProperties.com and our subsidiaries and affiliates (collectively
            the “Company” or "FABOProperties.com") provide you with access to a
            variety of services, including but not limited to the
            www.FABOProperties.com website (the "Website") and
            FABOProperties.com's mobile applications (the “Mobile App”) and all
            the products and services available through our Website and Mobile
            App (collectively the "Services"). The Website and Mobile App is
            owned and operated by FABO Properties Private Limited, a company
            incorporated under the laws of India.
            <br />
            <br />
            This document and the Privacy Policy is an electronic record in
            terms of Information Technology Act, 2000 and rules there under as
            applicable and the amended provisions pertaining to electronic
            records in various statutes as amended by the Information Technology
            Act, 2000. These ‘Terms of Use’ constitute an electronic record
            within the meaning of the applicable law. This electronic record is
            generated by a computer system and does not require any physical or
            digital signatures.
            <br />
            <br />
            <span
              style={{
                fontWeight: "bold",
              }}
            >
              TO WHOM DOES THIS POLICY APPLY?{" "}
            </span>
            <br />
            <br />
            This Policy applies to all “Users” who uses our Services.
            <br />
            <br />
            <span
              style={{
                fontWeight: "bold",
              }}
            >
              WHAT INFORMATION DO WE COLLECT, AND WHERE DO WE GET IT FROM?{" "}
            </span>
            <br />
            <br />
            We collect information from anyone who uses our Services: We ask for
            some basic details from User including but not limited to their
            name, phone number, email address. Furthermore, like many online
            services, we use technologies like session and persistent cookies,
            web beacons (tiny image files on web pages that communicate
            information about the page viewer to the beacon owner), log data,
            and third-party analytics services to collect and analyze
            information about all users of our Services. This includes things
            like User search preferences, interaction with ads on our Services,
            and location.
            <br />
            <br />
            Our servers automatically record information ("Log Data") created by
            your use of the Services. Log Data may include information such as
            your IP address, browser type, operating system, the referring web
            page, pages visited, location, your mobile carrier, device, search
            terms, and cookie information. We receive Log Data when you interact
            with our Services, for example, when you visit our Website and / or
            Mobile App, sign into our Services, or interact with our email
            notifications. We use Log Data to provide our Services and to
            measure, customize, and improve them, as well as collect and use
            them in the aggregate. This policy does not apply to, nor do we take
            any responsibility for any information that is collected by any
            third party either using the Services or through any links on the
            Website and / or Mobile App or through any of the advertisements.
            <br />
            <br />
            Cookies are small data files that we transfer to your computer. We
            use "session" cookies to keep you logged in while you use our
            Services, to better understand how you interact with our Services,
            and to monitor aggregate usage and web traffic information on our
            Services. We use "persistent" cookies to recognize you each time you
            return to our Services. For example, we create a persistent cookie
            that includes some basic information about you, like your most
            recent search and preferences.
            <br />
            <br />
            Most internet browsers automatically accept cookies, but you can
            change your settings or use third-party tools to refuse cookies or
            prompt you before accepting cookies from the websites you visit. You
            can also use your browser settings or other tools to delete cookies
            you already have. Please be aware that some parts of our Services
            may not work for you if you disable cookies.
            <br />
            <br />
            Location Data: If you provide location information (like a ZIP code,
            street address, or even just a city) during the registration process
            or at any other time via your account settings, we will store that
            information and associate it with your account. We may use and store
            information about your location to provide localized features, to
            analyze our Services with the help of third-party analytics
            services, to provide you with relevant advertising and marketing
            recommendations, and otherwise to improve and customize our
            Services.
            <br />
            <br />
            <span
              style={{
                fontWeight: "bold",
              }}
            >
              WHY WE COLLECT INFORMATION FROM YOU?
            </span>
            <br />
            <br />
            FABOProperties.com provides digital real estate advertising /
            marketing and information services through its Website, Mobile App
            and other services. To provide our Services, we use the information
            we collect to: Help you find the most relevant information for your
            situation by customizing our Services to optimize your experience.
            Keep you connected with FABOProperties.com across the internet and
            update you with residential real estate-related news and
            information. Put you in touch with the right people to sell, buy,
            rent and to optimize the information, we share with those parties to
            initiate a productive and efficient relationship.
            <br />
            <br />
            Services Description: FABOProperties.com attempts to be as accurate
            as possible. However, FABOProperties.com does not warrant that
            descriptions of or content of this site is accurate, complete,
            reliable, current, or error-free. Also, your access to the Services
            may also be occasionally suspended or restricted to allow for
            repairs, maintenance, or the introduction of new facilities or at
            any time without prior notice. We will attempt to limit the
            frequency and duration of any such suspension or restriction.
            FABOProperties.com provides links to other sites over which
            FABOProperties.com has no control. FABOProperties.com is not
            responsible for the availability of such external sites or resources
            and does not endorse and is not responsible or liable for any
            content, advertising, products or other material on or available
            from such sites or resources.
            <br />
            <br />
            From time to time, we share the information of those who access our
            Services with the other reputable organizations whose products or
            services we think you might find interesting and suits to your
            requirements. If you do not want us to share your information with
            other companies or organizations, please let us know by emailing us
            at hello@FABOProperties.com.
            <br />
            <br />
            Persons who supply us with their telephone numbers online may
            receive telephone calls or text messages from us with information
            regarding new products or services or upcoming events. You hereby
            give specific consent to receive the telephone calls or text
            messages related to our Services and waive the DND registry in case
            you have subscribed to the same. If you do not wish to receive such
            telephone calls or text messages, please let us know by emailing us
            at hello@FABOProperties.com.
            <br />
            <br />
            With respect to Ad servers: To try and bring you offers that are of
            interest to you, we have relationships with other companies to whom
            we allow to place ads on our Website and Mobile App. As a result of
            your visit to our Website and / or Mobile App, ad server companies
            may collect information such as your domain type, your IP address
            and clickstream information.
            <br />
            <br />
            Direct contact with User: If you fill out a form to contact a Sales
            Expert (or use any other contact forms available on our Services) or
            request for a callback, we may share personally identifiable
            information that you share with us and information about your use of
            our Services with the party you wanted to contact. This may include
            data you input such as home search criteria or Log Data that we
            collect as you use the Services. Sometimes, if we are working with a
            third party to improve the quality of connect we provide to our
            users, we may provide that third party with additional but limited
            personally identifiable information for the sole purpose of their
            carrying out their duty to us. By sharing the information, you agree
            to share your details to a third party also.
          </Typography>
        </Box>
      </AppContainer>
    </Box>
  );
}
